// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_D2R8lBuiBd3Q8FLZF_QS2rWWngwnNVk',
    appId: '1:586130210166:android:65886e767bbf92c960ce57',
    messagingSenderId: '586130210166',
    projectId: 'parowanie-e0f5a',
    storageBucket: 'parowanie-e0f5a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd7ubJtkkqD94d6Mp7jvTS9B9C6gpDe8w',
    appId: '1:586130210166:ios:5c933348326757fa60ce57',
    messagingSenderId: '586130210166',
    projectId: 'parowanie-e0f5a',
    storageBucket: 'parowanie-e0f5a.appspot.com',
    iosClientId: '586130210166-l9rqpvp1ff3ln8ousit4e14sms07f013.apps.googleusercontent.com',
    iosBundleId: 'com.michalgudalewicz.parowanie',
  );
}
